motivation_paras = [
    "This report compares a simple differentially private histogram "
    "method on different values of epsilon, and different feature sets "
    "(ie, different sizes of feature space). "
    "The implementation uses the tumult-analytics library to manage "
    "histograms over very large feature spaces/cell counts. "
    "In this simple histogram algorithm, the added laplacian noise is "
    "the only source of perturbation; this means that high values of epsilon are very "
    "likely to preserve real, unique individuals from the ground truth data."
]

observation_paras = [
    "<ul class='ul-margin-bottom'>"
    "<li>"
    "<b>Considering Epsilon 10:</b> "
    "The sensitivity of a histogram is 1, so when epsilon is "
    "10 the scale of the laplace distribution is 1/10. "
    "The standard deviation of the laplace distribution with a scale of 0.1 is "
    "around 0.14 (ie, 1/10 of sqrt(2)). What that means is that when we round to "
    "integers, if we're using epsilon 10 on a simple DP histogram, most "
    "noise values will be much less than 1 and most counts won't change."
    "</li>"
    "<li>"
    "<b>Epsilon 10 and Unique Real People: </b>"
    "This means that unique individuals that exist in the target data are "
    "likely to also exist in the deidentified data. To disappear, a count of 1 "
    "in the target would need to sample a negative noise value less than -0.5 (if we're rounding). "
    "In fact (checking with a python script because the cdf for laplace on wikipedia is only "
    "good for scales >=1), it looks like there's a greater than 95% chance that the noise "
    "value sampled will not be a negative value less than -0.5. "
    "That means we'd expect around 95% of the unique individuals in the target "
    "data to also exist in the deidentified data (see the Unique Exact Match metric)."
    "</li>"
    "<li>"
    "<b>Epsilon 10 and Added Fake People: </b>"
    "However, in a histogram across a very large feature space, "
    "there's very many counts. The vast majority of these counts will be "
    "0 on the target data, but the added noise will turn around 5% of them into counts of 1 or greater. "
    "This is the added noise of people we can see apparently burying the target distribution in the Pair-wise "
    "PCA metric. But because these people are added uniformly randomly across the feature space, "
    "they have a different impact when we look at analyses that identify aggregate patterns in the data. "
    "On epsilon 10 these additions weaken regression metric without significantly biasing/changing it, "
    "and they only have a significant impact on some pairwise feature correlations."
    "</li>"
    "<li>"
    "<b>Other Epsilons: </b>"
    "The above privacy/accuracy properties change as the epsilon decreases. "
    "Some change more gradually/smoothly than others."
    "</ul>"
]